### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by ismith** [honeycombio/terraform-aws-honeycomb-cloudwatch-metric-stream#12]
- what do we test and how (`test.bats`)
- changelog
- tagging
- other steps needed by the public registry?

**Comment by jharley** [comment]
Closing this as we've deprecated the module in favor of Please use the [CloudWatch Metrics submodule](https://registry.terraform.io/modules/honeycombio/integrations/aws/latest/submodules/cloudwatch-metrics) included in the [Honeycomb AWS Integrations module](https://registry.terraform.io/modules/honeycombio/integrations/aws/latest).
