### ISSUE TITLE
AWS Provider Version Constraint limits use of 4.x provider in projects using this module

### ISSUE THREAD

**Issue by kpkrishnamoorthy** [honeycombio/terraform-aws-honeycomb-cloudwatch-metric-stream#19]
**Versions**
v0.2.3

**Steps to reproduce**

1. Set the AWS provider version constraint in the terraform root module to `~> 4.0`
2. Use the `honeycombio/honeycomb-cloudwatch-metric-stream/aws` module within the root module, as documented.
3. Run `terraform init --reconfigure --upgrade`

You will see the error "Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given constraints >= 3.42.0, ~> 4.0" output by terraform. The init command will fail, and plans/applies will not be possible.

**Additional context**
This error started after Hashicorp released version 4.x of their AWS provider. Setting the provider version to 3.x in the root module works; however it prevents one from using the latest AWS provider version in terraform projects that use this module.

This is because of the version constraint for the AWS provider encoded into this module, here: https://github.com/honeycombio/terraform-aws-honeycomb-cloudwatch-metric-stream/blob/bf005c4f460450b0fa190922f198f9bf77647f97/versions.tf#L7

**Comment by jharley** [comment]
Hi, @kpkrishnamoorthy.

I'm afraid I can't reproduce this behaviour. I just got version 0.2.3 and 0.3.1 (latest) of this module to init with the v4 AWS provider:

```
$ terraform init --upgrade
Upgrading modules...
Downloading registry.terraform.io/honeycombio/honeycomb-cloudwatch-metric-stream/aws 0.2.3. for honeycomb-cloudwatch-metric-stream...
- honeycomb-cloudwatch-metric-stream in .terraform/modules/honeycomb-cloudwatch-metric-stream

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 3.42.0, ~> 4.0"...
- Using previously-installed hashicorp/aws v4.4.0
```

Here is my HCL:

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4"
    }
  }
}

provider "aws" {
  region = "us-east-2"
}

variable "honeycomb_api_key" {
	# set as env var TF_VAR_honeycomb_api_key
}

module "honeycomb-cloudwatch-metric-stream" {
  source  = "honeycombio/honeycomb-cloudwatch-metric-stream/aws"
  version = "0.2.3"

  name                   = "my-cloudwatch-metrics"
  honeycomb_dataset_name = "my-cloudwatch-metrics"
  honeycomb_api_key      = var.honeycomb_api_key
}
```
